---
title: "Pretest"
author: "BUS 41911"
date: "Due 24 September 2018"
output:
  pdf_document:
    includes:
      in_header: ../support/boothmacros.tex
    number_sections: no
    template: ../support/dm-docs.tex
    toc: no
  html_document:
    theme: flatly
---

* Please complete this test by September 24 at 9am. I will use the results to better calibrate the course to student background. Email your answers to <daniel.mcdonald@chicagobooth.edu>.
* Please don't spend more than 1 hour.
* Please don't consult outside resources. The goal is to see what you know, not what you can find answers to. (Looking up the definition of a term you've heard before is fine, but try to stick to the spirit of the test. Use your best judgment.)
* This is graded but on completion only (full points if submitted, none if not).

1. What is your degree program and what are you hoping to learn from this class?

2. (Maximum likelihood) Let $X_1,\ldots,X_n$ be iid Gaussian
  random variables each with probability density function
  \[
  f_X(x;s) = \frac{1}{\sqrt{2\pi s}}\exp\left\{-\frac{x^2}{2s}\right\}.
  \]
  Find the maximum likelihood estimator for $s$. 

3. (Estimation) Let $\hat\theta$ be an estimator for $\theta$. Write the formula
  for the bias of $\hat\theta$. Is the MLE in the previous problem
  unbiased? Is it asymptotically unbiased?

4. (Risk analysis) Explain why we might prefer a biased estimator to an unbiased estimator.

6. (Convex optimization) Write down the Langrage Dual for the following optimization
  problem and explain the necessary conditions for the stationary
  point to be an optimum (you do not need to find the stationary
  point or perform any calculations):
  \begin{align*}
    & \min_b L(y,\mathbf{X} b)\\
    \textrm{subject to} &\quad \norm{Ab}^2 \leq C
  \end{align*}
  for some convex function $L: \R^n \rightarrow \R^+$, vectors $y \in \R^n$ and
  $b \in \R^p$, matrices $A \in \R^{m\times p}$ and $\mathbf{X} \in
  \R^{n\times p}$, and constant $C$. Here $\norm{\cdot}^2$ is the squared
  $\ell_2$-norm of a vector. That is $\norm{z}^2 = z^\top z$.

6. (Coding) What does the following `R` code do?
```{r, eval=FALSE}
x = 2*pi*runif(100)
y = sin(x) + rnorm(100)
B = splines::bs(x,20)
logSeq <- function(from=1e6, to=1, len=100){ 
  exp(seq(log(from),log(to),length.out = len))
}
lam = logSeq()
mod = MASS::lm.ridge(y~B, lambda=lam)
preds = cbind(1,B) %*% coef(mod)[which.min(mod$GCV),]
df = data.frame(y=y, x=x, truth=sin(x), preds=preds)
library(tidyverse)
df %>% gather(key="key",value="value",-x) %>%
  ggplot(aes(x=x,y=value,col=key)) + geom_line() + ylab('') +
  theme_minimal()
```